-- Load G-NAF PSV files into SQL Server tables.
-- Requires SQLCMD mode for $(BasePath) variable expansion.
-- Update BasePath to the folder that contains "Standard" and "Authority Code".
-- Example (sqlcmd): sqlcmd -S . -d "g-naf_2020" -v BasePath="C:\\data\\G-NAF NOVEMBER 2025" -i import_psv_sqlserver.sql
-- Example (SSMS): enable SQLCMD mode, then edit BasePath below.

:setvar BasePath "C:\\path\\to\\G-NAF NOVEMBER 2025"

USE [g-naf_2020];
GO
SET NOCOUNT ON;
GO
PRINT 'Loading ADDRESS_ALIAS_TYPE_AUT from Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_CHANGE_TYPE_AUT from Authority_Code_ADDRESS_CHANGE_TYPE_AUT_psv.psv';
BULK INSERT dbo.ADDRESS_CHANGE_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_ADDRESS_CHANGE_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_TYPE_AUT from Authority_Code_ADDRESS_TYPE_AUT_psv.psv';
BULK INSERT dbo.ADDRESS_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_ADDRESS_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading FLAT_TYPE_AUT from Authority_Code_FLAT_TYPE_AUT_psv.psv';
BULK INSERT dbo.FLAT_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_FLAT_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading GEOCODED_LEVEL_TYPE_AUT from Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv.psv';
BULK INSERT dbo.GEOCODED_LEVEL_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading GEOCODE_RELIABILITY_AUT from Authority_Code_GEOCODE_RELIABILITY_AUT_psv.psv';
BULK INSERT dbo.GEOCODE_RELIABILITY_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_GEOCODE_RELIABILITY_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading GEOCODE_TYPE_AUT from Authority_Code_GEOCODE_TYPE_AUT_psv.psv';
BULK INSERT dbo.GEOCODE_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_GEOCODE_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LEVEL_TYPE_AUT from Authority_Code_LEVEL_TYPE_AUT_psv.psv';
BULK INSERT dbo.LEVEL_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_LEVEL_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS_TYPE_AUT from Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_CLASS_AUT from Authority_Code_LOCALITY_CLASS_AUT_psv.psv';
BULK INSERT dbo.LOCALITY_CLASS_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_LOCALITY_CLASS_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_MATCH_CODE_AUT from Authority_Code_MB_MATCH_CODE_AUT_psv.psv';
BULK INSERT dbo.MB_MATCH_CODE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_MB_MATCH_CODE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PS_JOIN_TYPE_AUT from Authority_Code_PS_JOIN_TYPE_AUT_psv.psv';
BULK INSERT dbo.PS_JOIN_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_PS_JOIN_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_CLASS_AUT from Authority_Code_STREET_CLASS_AUT_psv.psv';
BULK INSERT dbo.STREET_CLASS_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_STREET_CLASS_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS_TYPE_AUT from Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_SUFFIX_AUT from Authority_Code_STREET_SUFFIX_AUT_psv.psv';
BULK INSERT dbo.STREET_SUFFIX_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_STREET_SUFFIX_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_TYPE_AUT from Authority_Code_STREET_TYPE_AUT_psv.psv';
BULK INSERT dbo.STREET_TYPE_AUT
FROM '$(BasePath)\Authority Code\Authority_Code_STREET_TYPE_AUT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from ACT_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\ACT_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from ACT_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\ACT_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from ACT_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\ACT_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from ACT_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\ACT_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from ACT_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\ACT_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from ACT_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\ACT_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from ACT_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\ACT_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from ACT_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\ACT_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from ACT_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\ACT_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from ACT_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\ACT_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from ACT_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\ACT_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from ACT_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\ACT_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from ACT_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\ACT_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from ACT_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\ACT_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from ACT_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\ACT_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from ACT_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\ACT_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from ACT_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\ACT_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from ACT_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\ACT_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from ACT_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\ACT_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from NSW_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\NSW_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from NSW_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\NSW_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from NSW_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\NSW_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from NSW_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\NSW_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from NSW_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\NSW_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from NSW_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\NSW_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from NSW_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\NSW_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from NSW_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\NSW_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from NSW_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\NSW_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from NSW_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\NSW_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from NSW_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\NSW_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from NSW_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\NSW_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from NSW_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\NSW_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from NSW_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\NSW_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from NSW_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\NSW_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from NSW_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\NSW_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from NSW_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\NSW_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from NSW_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\NSW_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from NSW_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\NSW_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from NT_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\NT_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from NT_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\NT_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from NT_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\NT_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from NT_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\NT_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from NT_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\NT_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from NT_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\NT_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from NT_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\NT_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from NT_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\NT_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from NT_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\NT_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from NT_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\NT_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from NT_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\NT_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from NT_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\NT_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from NT_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\NT_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from NT_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\NT_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from NT_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\NT_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from NT_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\NT_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from NT_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\NT_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from NT_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\NT_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from NT_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\NT_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from OT_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\OT_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from OT_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\OT_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from OT_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\OT_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from OT_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\OT_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from OT_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\OT_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from OT_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\OT_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from OT_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\OT_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from OT_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\OT_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from OT_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\OT_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from OT_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\OT_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from OT_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\OT_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from OT_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\OT_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from OT_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\OT_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from OT_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\OT_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from OT_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\OT_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from OT_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\OT_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from OT_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\OT_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from OT_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\OT_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from OT_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\OT_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from QLD_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\QLD_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from QLD_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\QLD_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from QLD_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\QLD_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from QLD_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\QLD_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from QLD_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\QLD_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from QLD_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\QLD_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from QLD_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\QLD_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from QLD_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\QLD_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from QLD_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\QLD_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from QLD_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\QLD_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from QLD_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\QLD_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from QLD_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\QLD_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from QLD_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\QLD_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from QLD_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\QLD_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from QLD_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\QLD_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from QLD_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\QLD_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from QLD_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\QLD_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from QLD_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\QLD_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from QLD_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\QLD_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from SA_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\SA_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from SA_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\SA_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from SA_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\SA_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from SA_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\SA_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from SA_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\SA_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from SA_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\SA_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from SA_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\SA_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from SA_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\SA_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from SA_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\SA_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from SA_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\SA_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from SA_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\SA_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from SA_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\SA_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from SA_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\SA_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from SA_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\SA_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from SA_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\SA_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from SA_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\SA_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from SA_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\SA_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from SA_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\SA_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from SA_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\SA_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from TAS_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\TAS_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from TAS_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\TAS_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from TAS_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\TAS_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from TAS_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\TAS_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from TAS_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\TAS_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from TAS_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\TAS_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from TAS_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\TAS_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from TAS_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\TAS_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from TAS_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\TAS_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from TAS_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\TAS_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from TAS_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\TAS_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from TAS_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\TAS_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from TAS_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\TAS_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from TAS_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\TAS_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from TAS_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\TAS_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from TAS_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\TAS_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from TAS_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\TAS_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from TAS_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\TAS_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from TAS_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\TAS_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from VIC_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\VIC_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from VIC_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\VIC_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from VIC_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\VIC_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from VIC_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\VIC_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from VIC_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\VIC_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from VIC_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\VIC_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from VIC_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\VIC_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from VIC_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\VIC_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from VIC_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\VIC_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from VIC_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\VIC_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from VIC_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\VIC_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from VIC_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\VIC_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from VIC_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\VIC_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from VIC_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\VIC_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from VIC_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\VIC_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from VIC_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\VIC_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from VIC_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\VIC_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from VIC_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\VIC_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from VIC_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\VIC_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_ALIAS from WA_ADDRESS_ALIAS_psv.psv';
BULK INSERT dbo.ADDRESS_ALIAS
FROM '$(BasePath)\Standard\WA_ADDRESS_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DEFAULT_GEOCODE from WA_ADDRESS_DEFAULT_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_DEFAULT_GEOCODE
FROM '$(BasePath)\Standard\WA_ADDRESS_DEFAULT_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_DETAIL from WA_ADDRESS_DETAIL_psv.psv';
BULK INSERT dbo.ADDRESS_DETAIL
FROM '$(BasePath)\Standard\WA_ADDRESS_DETAIL_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_FEATURE from WA_ADDRESS_FEATURE_psv.psv';
BULK INSERT dbo.ADDRESS_FEATURE
FROM '$(BasePath)\Standard\WA_ADDRESS_FEATURE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2016 from WA_ADDRESS_MESH_BLOCK_2016_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2016
FROM '$(BasePath)\Standard\WA_ADDRESS_MESH_BLOCK_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_MESH_BLOCK_2021 from WA_ADDRESS_MESH_BLOCK_2021_psv.psv';
BULK INSERT dbo.ADDRESS_MESH_BLOCK_2021
FROM '$(BasePath)\Standard\WA_ADDRESS_MESH_BLOCK_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE_GEOCODE from WA_ADDRESS_SITE_GEOCODE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE_GEOCODE
FROM '$(BasePath)\Standard\WA_ADDRESS_SITE_GEOCODE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading ADDRESS_SITE from WA_ADDRESS_SITE_psv.psv';
BULK INSERT dbo.ADDRESS_SITE
FROM '$(BasePath)\Standard\WA_ADDRESS_SITE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_ALIAS from WA_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.LOCALITY_ALIAS
FROM '$(BasePath)\Standard\WA_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_NEIGHBOUR from WA_LOCALITY_NEIGHBOUR_psv.psv';
BULK INSERT dbo.LOCALITY_NEIGHBOUR
FROM '$(BasePath)\Standard\WA_LOCALITY_NEIGHBOUR_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY_POINT from WA_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.LOCALITY_POINT
FROM '$(BasePath)\Standard\WA_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading LOCALITY from WA_LOCALITY_psv.psv';
BULK INSERT dbo.LOCALITY
FROM '$(BasePath)\Standard\WA_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2016 from WA_MB_2016_psv.psv';
BULK INSERT dbo.MB_2016
FROM '$(BasePath)\Standard\WA_MB_2016_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading MB_2021 from WA_MB_2021_psv.psv';
BULK INSERT dbo.MB_2021
FROM '$(BasePath)\Standard\WA_MB_2021_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading PRIMARY_SECONDARY from WA_PRIMARY_SECONDARY_psv.psv';
BULK INSERT dbo.PRIMARY_SECONDARY
FROM '$(BasePath)\Standard\WA_PRIMARY_SECONDARY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STATE from WA_STATE_psv.psv';
BULK INSERT dbo.STATE
FROM '$(BasePath)\Standard\WA_STATE_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_ALIAS from WA_STREET_LOCALITY_ALIAS_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_ALIAS
FROM '$(BasePath)\Standard\WA_STREET_LOCALITY_ALIAS_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY_POINT from WA_STREET_LOCALITY_POINT_psv.psv';
BULK INSERT dbo.STREET_LOCALITY_POINT
FROM '$(BasePath)\Standard\WA_STREET_LOCALITY_POINT_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

PRINT 'Loading STREET_LOCALITY from WA_STREET_LOCALITY_psv.psv';
BULK INSERT dbo.STREET_LOCALITY
FROM '$(BasePath)\Standard\WA_STREET_LOCALITY_psv.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0d0a', TABLOCK, CODEPAGE = '65001');
GO

