CREATE OR ALTER VIEW READABLE_ADDRESS_VIEW

AS

SELECT
  AV.ADDRESS_DETAIL_PID AS ADDRESS_DETAIL_PID,
  AV.STREET_LOCALITY_PID AS STREET_LOCALITY_PID,
  AV.LOCALITY_PID AS LOCALITY_PID,
  AV.BUILDING_NAME AS BUILDING_NAME,

  AV.LOT_NUMBER_PREFIX AS LOT_NUMBER_PREFIX,
  AV.LOT_NUMBER AS LOT_NUMBER,
  AV.LOT_NUMBER_SUFFIX AS LOT_NUMBER_SUFFIX,

  AV.FLAT_TYPE AS FLAT_TYPE,
  AV.FLAT_NUMBER_PREFIX AS FLAT_NUMBER_PREFIX,
  AV.FLAT_NUMBER AS FLAT_NUMBER,
  AV.FLAT_NUMBER_SUFFIX AS FLAT_NUMBER_SUFFIX,

  AV.LEVEL_TYPE AS LEVEL_TYPE,
  AV.LEVEL_NUMBER_PREFIX AS LEVEL_NUMBER_PREFIX,
  AV.LEVEL_NUMBER AS LEVEL_NUMBER,
  AV.LEVEL_NUMBER_SUFFIX AS LEVEL_NUMBER_SUFFIX,

  AV.NUMBER_FIRST_PREFIX AS NUMBER_FIRST_PREFIX,
  AV.NUMBER_FIRST AS NUMBER_FIRST,
  AV.NUMBER_FIRST_SUFFIX AS NUMBER_FIRST_SUFFIX,
  AV.NUMBER_LAST_PREFIX AS NUMBER_LAST_PREFIX,
  AV.NUMBER_LAST AS NUMBER_LAST,
  AV.NUMBER_LAST_SUFFIX AS NUMBER_LAST_SUFFIX,

  AV.STREET_NAME AS STREET_NAME,
  AV.STREET_CLASS_TYPE AS STREET_CLASS_TYPE,
  STA.DESCRIPTION AS STREET_TYPE_ABBREVIATION,
  AV.STREET_SUFFIX_TYPE AS STREET_SUFFIX_TYPE,

  AV.LOCALITY_NAME AS LOCALITY_NAME,
  AV.STATE_ABBREVIATION AS STATE_ABBREVIATION,
  AV.POSTCODE AS POSTCODE,

  CONCAT_WS(', ',
    NULLIF(TRIM(AV.BUILDING_NAME), ''),
    NULLIF(TRIM(CONCAT_WS(' ',
      NULLIF(TRIM(CONCAT_WS(' ',
        AV.FLAT_TYPE,
        NULLIF(TRIM(CONCAT_WS('', AV.FLAT_NUMBER_PREFIX, AV.FLAT_NUMBER, AV.FLAT_NUMBER_SUFFIX)), '')
      )), ''),
      NULLIF(TRIM(CONCAT_WS(' ',
        AV.LEVEL_TYPE,
        NULLIF(TRIM(CONCAT_WS('', AV.LEVEL_NUMBER_PREFIX, AV.LEVEL_NUMBER, AV.LEVEL_NUMBER_SUFFIX)), '')
      )), '')
    )), ''),
    NULLIF(TRIM(
      CASE
        WHEN AV.NUMBER_FIRST IS NOT NULL THEN
          CONCAT_WS('',
            CONCAT_WS('', AV.NUMBER_FIRST_PREFIX, AV.NUMBER_FIRST, AV.NUMBER_FIRST_SUFFIX),
            CASE
              WHEN AV.NUMBER_LAST IS NOT NULL THEN CONCAT('-', CONCAT_WS('', AV.NUMBER_LAST_PREFIX, AV.NUMBER_LAST, AV.NUMBER_LAST_SUFFIX))
              ELSE ''
            END
          )
        WHEN AV.LOT_NUMBER IS NOT NULL THEN
          CONCAT_WS('',
            'LOT ',
            CONCAT_WS('', AV.LOT_NUMBER_PREFIX, AV.LOT_NUMBER, AV.LOT_NUMBER_SUFFIX)
          )
        ELSE NULL
      END
    ), ''),
    NULLIF(TRIM(CONCAT_WS(' ',
      AV.STREET_NAME,
      STA.DESCRIPTION,
      AV.STREET_SUFFIX_TYPE
    )), ''),
    NULLIF(TRIM(CONCAT_WS(' ', AV.LOCALITY_NAME, AV.STATE_ABBREVIATION, AV.POSTCODE)), '')
  ) AS READABLE_ADDRESS

FROM ADDRESS_VIEW AV
LEFT JOIN STREET_TYPE_AUT STA ON AV.STREET_TYPE_CODE = STA.CODE;
